db:
  url: jdbc:postgresql://localhost:5432/Diary-db?stringtype=unspecified
  username: postgres
  password: postgres
  hikari:
    max-pool-size: 10
  driver:
    classname: org.postgresql.Driver